sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tKr5ZzpE1BRJ4yHGEVQ
    access-key-secret: DqZAfe3cXfX79J72RmcszqEX0wG3D5
    bucket-name: wzb-study

  redis:
    host: localhost
    port: 6379
    password: 262460
    database: 0

  wechat:
    appid: wxf248bb3cbecdf8b0
    secret: e1476dfdb10be16941a4010e4c94d435
